#!/bin/bash

# for t in "past" "crop" "ntrl" "scnd" "range"
for t in "past" "crop" "ntrl"
do

cat << EOF
# montly land output
"land_month_${t}",       1,  "months", 1, "days", "time"
#
"land",                 "geolon_t",             "geolon_t", "land_month_${t}", "all", .false., "none", 1
"land",                 "geolat_t",             "geolat_t", "land_month_${t}", "all", .false., "none", 1
#
"land",                "area_${t}",                 "area", "land_month_${t}", "all", .true., "none", 2
#
"land",                "evap_${t}",                 "evap", "land_month_${t}", "all", .true., "none", 2
"land",              "fevapv_${t}",               "fevapv", "land_month_${t}", "all", .true., "none", 2
"land",                 "flw_${t}",                  "flw", "land_month_${t}", "all", .true., "none", 2
"land",                 "fsw_${t}",                  "fsw", "land_month_${t}", "all", .true., "none", 2
"land",                "FWSv_${t}",                 "FWSv", "land_month_${t}", "all", .true., "none", 2
"land",           "grnd_flux_${t}",            "grnd_flux", "land_month_${t}", "all", .true., "none", 2
"land",              "levapv_${t}",               "levapv", "land_month_${t}", "all", .true., "none", 2
"land",                "LWSv_${t}",                 "LWSv", "land_month_${t}", "all", .true., "none", 2
"land",                "runf_${t}",                 "runf", "land_month_${t}", "all", .true., "none", 2
"land",                "sens_${t}",                 "sens", "land_month_${t}", "all", .true., "none", 2
"land",                "snow_${t}",                 "snow", "land_month_${t}", "all", .true., "none", 2
"land",                 "Tca_${t}",                  "Tca", "land_month_${t}", "all", .true., "none", 2
"land",               "Tgrnd_${t}",                "Tgrnd", "land_month_${t}", "all", .true., "none", 2
"vegn",                "temp_${t}",                "Tvegn", "land_month_${t}", "all", .true., "none", 2
"land",              "transp_${t}",               "transp", "land_month_${t}", "all", .true., "none", 2
"land",               "water_${t}",                "water", "land_month_${t}", "all", .true., "none", 2
"soil",               "asoil_${t}",                "asoil", "land_month_${t}", "all", .true., "none", 2
"vegn",                  "bl_${t}",                   "bl", "land_month_${t}", "all", .true., "none", 2
"vegn",                  "br_${t}",                   "br", "land_month_${t}", "all", .true., "none", 2
"vegn",                 "bsw_${t}",                  "bsw", "land_month_${t}", "all", .true., "none", 2
"vegn",               "bwood_${t}",                "bwood", "land_month_${t}", "all", .true., "none", 2
"vegn",               "bseed_${t}",                "bseed", "land_month_${t}", "all", .true., "none", 2
"vegn",                 "nsc_${t}",                  "nsc", "land_month_${t}", "all", .true., "none", 2
"vegn",                "btot_${t}",                 "btot", "land_month_${t}", "all", .true., "none", 2
"land",                "Ctot_${t}",                 "Ctot", "land_month_${t}", "all", .true., "none", 2
"soil",                 "fsc_${t}",                  "fsc", "land_month_${t}", "all", .true., "none", 2
"soil",                 "ssc_${t}",                  "ssc", "land_month_${t}", "all", .true., "none", 2
"vegn",         "csmoke_rate_${t}",          "csmoke_rate", "land_month_${t}", "all", .true., "none", 2
"vegn",                 "lai_${t}",                  "lai", "land_month_${t}", "all", .true., "none", 2
"vegn",                 "sai_${t}",                  "sai", "land_month_${t}", "all", .true., "none", 2
"vegn",                 "gpp_${t}",                  "gpp", "land_month_${t}", "all", .true., "none", 2
"vegn",                 "npp_${t}",                  "npp", "land_month_${t}", "all", .true., "none", 2
"vegn",               "an_op_${t}",                "an_op", "land_month_${t}", "all", .true., "none", 2
"vegn",               "an_cl_${t}",                "an_cl", "land_month_${t}", "all", .true., "none", 2
"vegn",                "resp_${t}",                 "resp", "land_month_${t}", "all", .true., "none", 2
"soil",               "rsoil_${t}",                "rsoil", "land_month_${t}", "all", .true., "none", 2
"vegn",               "theta_${t}",                "theta", "land_month_${t}", "all", .true., "none", 2
"vegn",            "tsoil_av_${t}",             "tsoil_av", "land_month_${t}", "all", .true., "none", 2
"vegn",      "past_harv_rate_C_${t}",       "past_harv_rate_C", "land_month_${t}", "all", .true., "none", 2
"vegn",      "crop_harv_rate_C_${t}",       "crop_harv_rate_C", "land_month_${t}", "all", .true., "none", 2
"vegn", "wood_fast_harv_rate_C_${t}",  "wood_fast_harv_rate_C", "land_month_${t}", "all", .true., "none", 2
"vegn",  "wood_med_harv_rate_C_${t}",   "wood_med_harv_rate_C", "land_month_${t}", "all", .true., "none", 2
"vegn", "wood_slow_harv_rate_C_${t}",  "wood_slow_harv_rate_C", "land_month_${t}", "all", .true., "none", 2
"vegn",   "cleared_harv_rate_C_${t}",    "cleared_harv_rate_C", "land_month_${t}", "all", .true., "none", 2
"vegn",             "nindivs_${t}",              "nindivs", "land_month_${t}", "all", .true., "none", 2
"vegn",            "ncohorts_${t}",             "ncohorts", "land_month_${t}", "all", .true., "none", 2
"vegn",             "nlayers_${t}",              "nlayers", "land_month_${t}", "all", .true., "none", 2
# ====================
# INSTANTANEOUS OUTPUT
# ====================
"land_month_inst_${t}", 1, "months", 1, "days", "time"
#
"land",                 "geolon_t",             "geolon_t", "land_month_inst_${t}", "all", .false., "none", 1
"land",                 "geolat_t",             "geolat_t", "land_month_inst_${t}", "all", .false., "none", 1
#
"land",                "area_${t}",                 "area", "land_month_inst_${t}", "all", .false., "none", 2
#
"land",                "frac_${t}",                 "frac", "land_month_inst_${t}", "all", .false., "none", 2
"vegn",                  "bl_${t}",                   "bl", "land_month_inst_${t}", "all", .false., "none", 2
"vegn",                  "br_${t}",                   "br", "land_month_inst_${t}", "all", .false., "none", 2
"vegn",                 "bsw_${t}",                  "bsw", "land_month_inst_${t}", "all", .false., "none", 2
"vegn",               "bwood_${t}",                "bwood", "land_month_inst_${t}", "all", .false., "none", 2
"vegn",               "bseed_${t}",                "bseed", "land_month_inst_${t}", "all", .false., "none", 2
"vegn",                 "nsc_${t}",                  "nsc", "land_month_inst_${t}", "all", .false., "none", 2
"vegn",                "btot_${t}",                 "btot", "land_month_inst_${t}", "all", .false., "none", 2
"land",                "Ctot_${t}",                 "Ctot", "land_month_inst_${t}", "all", .false., "none", 2
"soil",                 "fsc_${t}",                  "fsc", "land_month_inst_${t}", "all", .false., "none", 2
"soil",                 "ssc_${t}",                  "ssc", "land_month_inst_${t}", "all", .false., "none", 2
"vegn",              "csmoke_${t}",               "csmoke", "land_month_inst_${t}", "all", .false., "none", 2
"vegn",               "afire_${t}",                "afire", "land_month_inst_${t}", "all", .false., "none", 2
"vegn",      "past_harv_pool_C_${t}",       "past_harv_pool_C", "land_month_inst_${t}", "all", .false., "none", 2
"vegn",      "crop_harv_pool_C_${t}",       "crop_harv_pool_C", "land_month_inst_${t}", "all", .false., "none", 2
"vegn",   "cleared_harv_pool_C_${t}",    "cleared_harv_pool_C", "land_month_inst_${t}", "all", .false., "none", 2
"vegn", "wood_fast_harv_pool_C_${t}",  "wood_fast_harv_pool_C", "land_month_inst_${t}", "all", .false., "none", 2
"vegn",  "wood_med_harv_pool_C_${t}",   "wood_med_harv_pool_C", "land_month_inst_${t}", "all", .false., "none", 2
"vegn", "wood_slow_harv_pool_C_${t}",  "wood_slow_harv_pool_C", "land_month_inst_${t}", "all", .false., "none", 2
"vegn",                 "ncm_${t}",                  "ncm", "land_month_inst_${t}", "all", .false., "none", 2
#
EOF

done

